# Site settings
title: Minh's Netlify Profile
email: mhnguyen289@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stay Hungry. Stay foolish.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mhnguyen289
github_username:  mhnguyen289

# Build settings
markdown: kramdown
gems:
 - jekyll-redirect-from

# redirect_from:
# title: Redirect link
# - [/netlify/anything]: https://minhs-netlify-sample-27331.netlify.com/netlify/anything
# - [/netlify/about/]: https://minhs-netlify-sample-27331.netlify.com/about/